# Generated by Django 2.2.2 on 2019-06-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdata',
            name='http_method',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='logdata',
            name='referer',
            field=models.CharField(max_length=500),
        ),
    ]
